wcコマンドを追加しました
kayama3/ruby-practices pull request #10
Opened 2022-12-02 11:11 UTC by kayama3

2022-12-02 13:29 UTC, kayama3 commented
https://github.com/kayama3/ruby-practices/blob/2161c19edf83729d584c6e6acf60af47a9ada693/06.wc/wc.rb#L23-L25
ファイル名を出力するこの処理について分からないことがあるので、質問させてください。
今のままだと、`ruby wc.rb`だけ実行した場合、出力結果が以下の様になってしまいます。
```
❯ ruby wc.rb
aaaaaaaaaa
       1       1      11 -
```
この`-`を表示しない様にしたいのですが、その方法がわかりません。

- `-`は`ARGF.class#filename`の仕様で、標準入力に対して返していると言うこと

この点については理解しているのですが、「標準入力である場合に`-`を表示しない様にする」と言う場合わけの方法が思いつきません。
このことについて、ヒントをお願いします🙇🏻‍♂️

2022-12-11 13:51 UTC, u1tnk requested changes
細かいところはコメントしました。

全体的な話として

- lines_words_bytes という名前は長い上、かなり頻出なのでオプション次第では中身が欠けたりするので正確性の点でも違和感があります。共通化した名前をつけましょう。このプログラムを読んで理解できれば良いので、ちょっと抽象的なものでも大丈夫です。
- [マトリョーシカ人形のようなメソッド設計を避ける | FBC](https://bootcamp.fjord.jp/pages/avoid-matroska-design) になってしまっているので、読んでみて改善してみてください。

2022-12-11 13:51 UTC, u1tnk commented on 06.wc/wc.rb
> +  if params.values.any? == false
rubyで  `hoge == boolean`は書かないです。 `if !hoge`にするか `unless hoge`にしましょう。

2022-12-11 13:51 UTC, u1tnk commented on 06.wc/wc.rb
> +  return unless ARGF.lineno > 1
この前後で 標準入力のときと分けていると思いますが、前後で同じ処理があるので共通化したいですね。

色んなところでARGFを読みこんでいるのが複雑化させていると思います。
読み込みは一箇所にまとめてファイル名と中身(どちらも単純な文字列)をハッシュなり配列なりでまとめる処理を行って、その後に表示するようにすればスッキリすると思います。

2022-12-11 13:51 UTC, u1tnk commented on 06.wc/wc.rb
> +def get_total_lines_words_bytes(argf, total_lines_words_bytes)
rubyの命名の慣例的に `get_`は付けません。この場合は `total_lines_words_bytes`で良いですね。
変数と見分けがつかないと思われると思いますが、そちらの方が読みやすいという考え方です。

2022-12-11 13:51 UTC, u1tnk commented on 06.wc/wc.rb
> +  Hash[*ary.flatten]
一時的でも aryという変数名は慣習的に使わないです。
この場合なら変数名無しで良いと思います。

`[sorted_options_key, calc_total_lines_words_bytes].transpose.flatten.to_h` 
で同じになると思います。

2022-12-11 13:51 UTC, u1tnk commented on 06.wc/wc.rb
> +  options_key_order = %w[l w c]
これは固定の文字列なのでメソッドの外に出して定数にすると良いですね。

2022-12-14 15:20 UTC, kayama3 commented
メソッド設計と、メソッド名、変数名を変更したので、確認をよろしくお願いします🙇🏻‍♂️

2022-12-14 15:51 UTC, kayama3 commented
https://github.com/kayama3/ruby-practices/blob/0cf32b53cd9da5de41e53fc732fb365ba30c5d32/06.wc/wc.rb#L53-L60
この箇所で行数、単語数、バイト数、ファイル名をそれぞれ配列に追加して並べ替えるという処理をしているのですが、`sizes_names <<`という形がずらずらと続くのが気になります。
この箇所をもう少しコンパクトに書くことはできないかと悩んだのですが、短く簡潔な処理が思いつかなかった次第です。
何か良い方法があれば教えていただきたいです🙏

2022-12-15 16:06 UTC, u1tnk requested changes
マトリョーシカは解決してメインの流れは見やすくはなったのですが、ちょっとmain内が混みあっていそうです。

- optionなどの入力の処理
- ファイルの読み込み
- 文字列の計算、整理
- 出力

のおおまかな流れがぱっと見で分かるように整理されてると良いですね。

また、全体的にマトリョーシカは良くないのですが、親子関係にあるようなものは内部で呼んであげた方が分かりやすいです。
例えば number_of_xxxxメソッドたちは全て同じ順番のfile_contentsが来ることを期待していて、相互に依存しています。
こういうのはまとめた親メソッドから呼ぶと良いと思います。
他にも同様の例が多そうですが、データ構造を見直すと良いと思います。

`names = [a.txt, b.txt]`
`contents = [a.txtの中身, b.txtの中身]`

のようなものよりも、例としてhashを使うと
```
files = [
{name: "a.txt", content: "a.txtの中身"},
{name: "b.txt", content: "b.txtの中身"},
]
```

となるようにした方がa.txtの情報セットという形で取り出せますね。もちろんcountなどもこのhashに入れてしまえば良いと思います。

2022-12-15 16:06 UTC, u1tnk commented on 06.wc/wc.rb
> +  input = {}
inputメソッド内でinputという名前の変数を使うのは動くのですが危険です。メソッド名を xxx_inputにすると良いかと思います。

2022-12-15 16:06 UTC, u1tnk commented on 06.wc/wc.rb
> +    return unless ARGF.lineno > 1
outputは最後の処理だと思うのですが、中身で突然ARGFが出てきて、引数だけで情報が足りないのが気になります。
既にtotalは計算していますし、引数の情報だけで判断できるのでは無いでしょうか？

2022-12-15 16:06 UTC, u1tnk commented on 06.wc/wc.rb
> +OPTIONS_KEY = params.keys
オプションを表すのに optionという名前とparamという名前が混在していますね。

紹介したかもしれませんが弊ブログの [[初心者向け]変数の命名、基本のキ | u1tnk.log](https://u1tnk.github.io/blog/2022/12/04/naming_variable/) にある 「表記ゆれ」問題になると思うので合わせましょう。あわせて読んで頂けると参考になるかと思います。

この場合optionはoptparseも使っていますし paramではなくoptionで統一すると良いでしょう。

2022-12-15 16:09 UTC, u1tnk commented
> この箇所で行数、単語数、バイト数、ファイル名をそれぞれ配列に追加して並べ替えるという処理をしているのですが、sizes_names <<という形がずらずらと続くのが気になります。
この箇所をもう少しコンパクトに書くことはできないかと悩んだのですが、短く簡潔な処理が思いつかなかった次第です。
何か良い方法があれば教えていただきたいです🙏

こちらの質問ですが、単純に同様の処理をするのであれば十分に簡潔だと思います。
ですが、レビューコメントにあるようにデータ構造を整理すればoutput以外のところで出力用のソートやオプションによる出し分けなどを考える必要が無いので、結果として処理が変わると思います。

2022-12-16 14:16 UTC, kayama3 commented on 06.wc/wc.rb
> +  input = {}
すいません、これは`メソッド名と、そのメソッド内で扱う変数名を一致させる`のがまずいという意味でしょうか？
同じ名前にしなければいいのかと思い、メソッド名は`input`のまま、メソッド内で扱う変数名を`sizes_names`に変更したのですが、この変更はいけないでしょうか？
それと

> メソッド名を xxx_inputにすると良いかと思います。

とありますが、この形でどのように名前をつければ良いのか思いつかなかったので、一例を挙げていただけるとありがたいです。
`files_input`などでしょうか？
質問ばかりで申し訳ございません。🙇🏻‍♂️

2022-12-16 14:30 UTC, kayama3 commented
再びの確認をお願いします！
また、以下の箇所について質問しましたので、回答していただけるとありがたいです。
https://github.com/kayama3/ruby-practices/pull/10#discussion_r1049808057

2022-12-16 14:55 UTC, kayama3 commented
以下の箇所の条件分岐が多いために、rubocopをパスできませんでした。
（エラーメッセージ:`33:1: C: Metrics/PerceivedComplexity: Perceived complexity for output is too high. [13/8]`）
https://github.com/kayama3/ruby-practices/blob/9014e4eef8c94d89096831093561d67cf37759bf/06.wc/wc.rb#L33-L53
この問題の解決法が思いつかないので、お力を貸していただきたいです。

下に示したような条件分岐が多い箇所について、メソッドを定義することで無理やり解決する方法ぐらいしか思いつかなかったのですが、これでは再びマトリョーシカ人形のようなメソッド構造になってしまうので断念しました。
```
     sizes_names.each do |file| 
       print file[:lines] if option['l'] 
       print file[:words] if option['w'] 
       print file[:bytes] if option['c'] 
       puts file[:name] 
     end 
```

2022-12-17 15:37 UTC, u1tnk requested changes

2022-12-17 15:37 UTC, u1tnk commented on 06.wc/wc.rb
> +    sizes_names << { lines: argf.count("\n").to_s.rjust(8),
メソッドだったのをここに展開したと思うんですが、メソッド化してたのが悪いわけじゃないのでメソッドはそのままでも大丈夫でした。もちろん一行レベルなのでこれでも大丈夫です。

ただ、現状の設計だと、ここはデータを集める部分という位置づけでフォーマットはoutputの役割のはずなので `to_s.rjust(8)`があるのは良くないです。
フォーマットしてしまうとデータの利用用途が限られて柔軟性を損ないます。

2022-12-17 15:37 UTC, u1tnk commented on 06.wc/wc.rb
> +  sizes_names = []
`sizes_names`はちょっと違和感があります。 filesで良いと思います。

2022-12-17 15:37 UTC, u1tnk commented on 06.wc/wc.rb
> +    sizes_names << { lines: argf.count("\n").to_s.rjust(8),
キー名は一つのファイルの情報種別で、ここに配列が入ってるわけじゃないので複数形は違和感があります。
並列にnameがあって、ファイル情報が色々入っているところなので `line_count`とかが良いと思います。

2022-12-17 15:37 UTC, u1tnk commented on 06.wc/wc.rb
> +  { lines: sizes_names.map { |v| v[:lines].to_i }.sum.to_s.rjust(8),
- `map{...}.sum` になっているところは `sum {...}`だけで大丈夫です。
- ここも前述通り、 to_s.rjustは削除しましょう。
- メソッド名が sort_xxxxになっていますがsortしていません。

2022-12-17 15:37 UTC, u1tnk commented on 06.wc/wc.rb
> +def output(sizes_names, total_sizes, option)
> 下に示したような条件分岐が多い箇所について、メソッドを定義することで無理やり解決する方法ぐらいしか思いつかなかったのですが、これでは再びマトリョーシカ人形のようなメソッド構造になってしまうので断念しました。

まず、この部分の質問を頂きましたが、 私が指摘するように`file changes`タブ (https://github.com/kayama3/ruby-practices/pull/10/files) でこの部分を選択してコメントしてもらえるとスレッドになるし、この画面に指摘がまとまるので返答しやすいです。

回答の質問ですが、メソッド化するので良いです。

「マトリョーショカ人形のような」

とは、以下のようにあまり関係無いメソッドなども含めてメソッドの中で他のメソッドを呼ぶ構成にしてしまうことで、メソッドに共通処理をまとめるのが悪いわけではありません。

```
- main
    - output 
        - input
            - sort ....
```

例えば以下のようにツリー状にしてinput/output専用の親子関係のような処理や共通で使う処理をメソッドにまとめて呼ぶのは良いです。mainの流れは分かりやすいですし、input/ouputはサブ機能のメイン処理のような役割となります。

```
- main
  - input
      - count_lines
    - output
        - output_line
```

ちなみにoutput_lineと書いているのが、rubocop対策で外出しにできそうなメソッドですが、これは 入力データを工夫して、totalでもファイルごとでも使えるようにすれば共通化もできます。これはrubocopが無くても指摘している内容なのでやってみましょう 💪

2022-12-20 14:18 UTC, u1tnk requested changes

2022-12-20 14:18 UTC, u1tnk commented on 06.wc/wc.rb
> +      puts v[:line_count].to_s.rjust(8) +
ほぼ一緒と思ったら共通化にチャレンジしましょう。

output_count では既に合計のときのnameを抽象化する事で共通化できているので、今度はoptionを抽象化すれば良いです。
ヒントとしては optionをそのまま使う必要は無いのでもっと使いやすいデータにすれば良いですよ。

2022-12-23 11:04 UTC, kayama3 commented on 06.wc/wc.rb
> +               name: ARGF.filename == '-' ? ' ' : " #{ARGF.filename}" }
`option`を`files`の中に一緒にしてしまうことで、`option`の抽象化をしました。
この点については合っているでしょうか？

2022-12-23 11:04 UTC, kayama3 commented on 06.wc/wc.rb
> +               name: ARGF.filename == '-' ? ' ' : " #{ARGF.filename}" }
https://github.com/kayama3/ruby-practices/blob/a69fd51cbd80b305e0125e366b2b0f3f2d70a4d3/06.wc/wc.rb#L27-L35
rubocop-fjordをパスしていない部分はここです。

2022-12-23 15:06 UTC, u1tnk commented on 06.wc/wc.rb
> +               name: ARGF.filename == '-' ? ' ' : " #{ARGF.filename}" }
> optionをfilesの中に一緒にしてしまうことで、optionの抽象化をしました。
この点については合っているでしょうか？

ちょっと想定と違います。
これだとfileごとにoptionが入るので全ファイルに同じ内容のオプションがコピーされていてデータの重複が大きいです。
また、同じものなのに別に保存するというのが良くなくて、何かの理由で一部が更新されてしまったら混乱を招きます。

だいぶ悩まれたと思うので、ヒントというかほぼ言ってしまうと、 options[:l] または引数無し(lwc全部表示)をまとめてしまうのが良いと思います。
optionsだと引数そのままと思ってしまいそうなので別の…例えば view_optionsとかの名前で保存してしまうと、その後引数無しの判定が不要になり、ここの部分も不要になるのでrubocopも問題無くなると思います。

2022-12-25 15:13 UTC, u1tnk requested changes

2022-12-25 15:13 UTC, u1tnk commented on 06.wc/wc.rb
> +  files = input
filesイコールinputだとちょっと違和感があるのでメソッド名は `parse_input`とすると inputを処理してfilesを取得したという意味とすると良いでしょう。

2022-12-25 15:13 UTC, u1tnk commented on 06.wc/wc.rb
> +  view_options = options(files, option)
ここはちょっと誤解を招いたようです。
main/inputなどで 以下の処理をしてその後で使いやすいようにoption情報を整理するという意味でした。
こうしておけば option指定が無いときの考慮は後でしなくても済むので。

```
view_options = {
  l: option['l'] || !options.any?,
  r: option['r'] || !options.any?,
  c: option['c'] || !options.any?,
}
```

2022-12-27 15:59 UTC, u1tnk requested changes
view_optionsの作り方は大丈夫です！

メソッド名だけ指摘していますので確認ください。

2022-12-27 15:59 UTC, u1tnk commented on 06.wc/wc.rb
> +  view_options = option
`view_optons`イコール `option`は違和感があります。 optionメソッドを `parse_view_options`あたりにすると良いかなと思います(parse部分はfetchとか他の単語でも良いです。ただ、get_にするとrubocopに指定されたりします。)

2022-12-27 15:59 UTC, u1tnk commented on 06.wc/wc.rb
> +  { line_count: (files.sum { |v| v[:line_count] } unless files[0][:line_count].nil?),
細かい部分ですが `v[:line_count].to_i` にすれば nil.to_iは0なので unlessが不要になると思います。

2022-12-28 02:27 UTC, kayama3 commented on 06.wc/wc.rb
> +  { line_count: (files.sum { |v| v[:line_count] } unless files[0][:line_count].nil?),
unless以下の処理はオプションを指定した場合の、parse_inputとtotal_sizesの各データの形を揃える意味で書いたのですが、不要だったでしょうか？
ご指摘の箇所のみを直した上で、例えばオプション`-lw`を指定した場合、`parse_input[:byte_count]`はnilになります。
しかし、`total_sizes[:byte_count]`は0になります。
以下は2つのファイルに対して、オプション`-lw`を指定したwcコマンドを実行した結果になります。
```
$ ruby wc.rb -lw  dummy_file1 dummy_file2
# parse_input [{:line_count=>99, :word_count=>244, :byte_count=>nil, :name=>" dummy_file1"}, {:line_count=>22, :word_count=>64, :byte_count=>nil, :name=>" dummy_file2"}]
# total_sizes {:line_count=>121, :word_count=>308, :byte_count=>0, :name=>" total"}
      99     244 dummy_file1
      22      64 dummy_file2
     121     308       0 total

```
個人的にはparse_inputとtotal_sizesの各データの形を揃えた方が、出力する段階でデータを扱いやすいと思ったのですが、出力する処理(output_countの部分)を工夫した方がいいでしょうか？

2022-12-28 07:08 UTC, u1tnk commented on 06.wc/wc.rb
> +  { line_count: (files.sum { |v| v[:line_count] } unless files[0][:line_count].nil?),
なるほど。
確かに現状でそこだけ nilチェックをやめたらおかしくなっちゃいますね。

> 個人的にはparse_inputとtotal_sizesの各データの形を揃えた方が、出力する段階でデータを扱いやすいと思ったのですが、出力する処理(output_countの部分)を工夫した方がいいでしょうか？

はい、計算するところは重い処理でも無いので、全て計算してデータを集めておいて、オプションによって表示を変える方がシンプルです。
Inputでやる方でもチェックが一箇所になるなら同じ量だし、指摘するほどでも無いかと思ってたんですが、total計算の方をシンプルにできないのであればやはりチェックを出力時のみにした方が良いと思います。

2022-12-28 12:52 UTC, u1tnk approved these changes

2023-05-18 10:14 UTC, merged