bowlingプログラムを追加しました。
kayama3/ruby-practices pull request #4
Opened 2022-08-08 15:12 UTC by kayama3

2022-08-15 14:06 UTC, u1tnk requested changes

2022-08-15 14:06 UTC, u1tnk commented on 04.bowling/bowling.rb
> +  elsif s == 'X' && shots.count >= 18
上の選択肢で `s == 'X' && shots.count < 18`なので、この選択肢で shots.countをチェックする意味は無いです。
とはいえ、見た目気持ち悪いので、この処理ならネストする事をおすすめします。以下みたいな感じです。

```
  if s == 'X' 
    shots << 10
    if shots.count < 18 
      shots << 0
    end
以下略
```

2022-08-16 06:51 UTC, kayama3 commented
プログラムの修正が完了したので、確認のほどよろしくお願いします。

2022-08-16 06:52 UTC, kayama3 commented on 04.bowling/bowling.rb
> +# frozen_string_literal: true
この部分なのですが、

2022-08-17 03:34 UTC, u1tnk commented on 04.bowling/bowling.rb
> +# frozen_string_literal: true
このコメントが何者かという事についてはググればたくさんでてきますので、分かりそうなサイトを見てみてください。ざっくり言うと、あった方がごくわずかに早くなったり安全になるよという感じです。

で、必要かどうかと言うと、「動作に必要は無いが、rubocop的には付ける事になっているので付けるべき」となります。
rubocop自体が「複数選択肢のある方針を機械的に一個で決めておいた方が統一できて読みやすくなるし揉めないよね」という目的のツールなので、どっちでも良い事はrubocopに従うのが基本です。
rubocopのデフォルト設定だと厳し過ぎるところもありますが、rubocop-fjord gemはプラクティス用に現実的にカスタマイズされているものなので、基本的に従うようにしてください。
もちろん理解できないところは質問頂いて構いません 💪

2022-08-17 03:35 UTC, u1tnk approved these changes

2022-08-17 03:35 UTC, u1tnk commented on 04.bowling/bowling.rb
> +    shots << 0 if shots.count < 18
ああ、サンプルで書いたのをrubocopに修正されましたね。 
確かに一行で書けました 😅

2022-09-12 02:10 UTC, merged